version: "3.9"
services:
  postgres:
    image: "postgres:13.4-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hohin
      POSTGRES_PASSWORD: hohin
      POSTGRES_DB: hohin
  mysql:
    image: "mysql:8.0"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: hohin
      MYSQL_USER: hohin
      MYSQL_PASSWORD: hohin
      MYSQL_DATABASE: hohin
  clickhouse:
    image: "clickhouse/clickhouse-server:23.3.8.21-alpine"
    ports:
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: hohin
      CLICKHOUSE_USER: hohin
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
      CLICKHOUSE_PASSWORD: hohin
    volumes:
      - ${PWD}/clickhouse.xml:/etc/clickhouse-server/users.xml
